default language: 'en' # The default language
bypass prefix: '>'
translate:
  chat: true
  server: true
  inventory: true
  commands in messages: false # Whether to translate messages that start with a command
messages:
  change: '&aLanguage successfully changed to %name%.'
  reset: '&aLanguage reset to %default%.'
  invalid: '&cInvalid language. Possible choices:'
debug: false

# keys: #Custom keys (only necessary if you want to use your own, it will automatically download a list of keys to use)
#   '0':
#     id: 'Tharsen'
#     secret: '6mutEwVfEVk3S9nIdolEc9EdVVHANwNyW69H15ssB7c='
#   '1':
#     id: 'Rell1936'
#     secret: 'ZiE7WrcOTj0QYuJsgan0PhQDRv2A34ZVIQKBWL7wS9o='
#   '2':
#     id: 'Faber1974'
#     secret: 'So3rU12SPzo2xjIICgyTPEoYxSIkAIKgopS1NOO/3jA='