name: Translate
main: com.pantherman594.translate.Main
description: Simple but effective translator!
depend: [ProtocolLib]
version: #VERSION#
author: PantherMan594
commands:
  language:
    aliases: [translate, lang]