name: Translate
main: com.pantherman594.translate.Main
description: Powerful and effective hands-free translator!
softdepend: [ProtocolLib, Factions]
version: #VERSION#
author: PantherMan594
commands:
  language:
    aliases: [translate, lang]